// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      //case TargetPlatform.windows:
      //  throw UnsupportedError(
      //    'DefaultFirebaseOptions have not been configured for windows - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      //  );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj6D5hQVP06qNAJObC4MEFqV6PeAKRR_k',
    appId: '1:505948333668:web:b41d958506689f4ae0e171',
    messagingSenderId: '505948333668',
    projectId: 'my-app-new-76fcd',
    authDomain: 'my-app-new-76fcd.firebaseapp.com',
    storageBucket: 'my-app-new-76fcd.appspot.com',
    measurementId: 'G-X51RFRS3VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfhR6jsI7vwvO3wp85xnS4iRZusFxD05E',
    appId: '1:505948333668:android:41b185bc8c5b61fee0e171',
    messagingSenderId: '505948333668',
    projectId: 'my-app-new-76fcd',
    storageBucket: 'my-app-new-76fcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaMdCtpJWu9g5Ff3o6pqThNFjvrazb9RY',
    appId: '1:505948333668:ios:2215ffd3b7de3f5ae0e171',
    messagingSenderId: '505948333668',
    projectId: 'my-app-new-76fcd',
    storageBucket: 'my-app-new-76fcd.appspot.com',
    iosBundleId: 'com.example.imagepicker',
  );
}
